config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index'

  resources :locations
  resources :events

  get 'example/form' => 'example#form'
  post 'example/form' => 'example#create'

  resources :job_applications
  # get 'job_application' => "job_applications#index"
  # get 'job_application/:id' => "job_applications#show"
  # get 'job_application/new' => "job_applications#new"
  # post 'job_application' => 'job_applications#create'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      redirect_back_or_to @event
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_path
    else
      redirect_to new_event_path
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def event_params
    params.require(:event).permit(:name, :data, :capacity)
  end
end

app/controllers/example_controller.rb
class ExampleController < ApplicationController
  def form
    @job_application = JobApplication.new
  end
  def create
  
    @job_application = JobApplication.new(params(:example))

    if @job_application.save
      redirect_to '/events'
    else
      render :form
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @locations = Location.all
    @events = Event.all
  end


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update(location_params)
      redirect_to @location
    else
      redirect_back_or_to @location
    end
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to locations_path
    else
      redirect_to new_location_path
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_path
  end

  def location_params
    params.require(:location).permit(:name, :city, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/events/_event_form.html.erb
<h1>New Event</h1>
<%= link_to 'Show all events', events_path %>

<%= form_for event do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/events/_single_event.html.erb
<div class="event">
  <h3><%= event.name%></h3>
  <%= link_to event.date, event_path(event) %>
</div>

app/views/events/edit.html.erb
events#edit page

<h1>Editing <%= link_to @event.name, event_path(@event) %></h1>
<%= render 'event_form', event: @event %>

app/views/events/index.html.erb
events#index page

<h1>Events</h1>
<%= link_to 'New Event', new_event_path %>
<% @events.each do |current_event| %>
<%= render 'single_event', event: current_event %>
<% end %>

app/views/events/new.html.erb
events#new page
<h1>New Event</h1>
<%= link_to 'See all events', events_path %>
<%= render 'event_form', event: @event %>

app/views/events/show.html.erb
events#show page
<h1><%= @event.name %></h1>

<%= render 'single_event', event: @event %>
<%= link_to 'Edit', edit_event_path(@event) %> | <%= link_to 'Delete', event_path(@event), method: :delete, data: {confirm: "please double check before you delete the event '#{@event.name}'?"} %>

app/views/example/form.html.erb
example@form page

<%= form_tag "/example/form" do %>
<div>
  Full name <br>
<%= text_field_tag :full_name %>
</div>
<div>
  Phone <br>
  <%= text_field_tag :phone %>
</div>
<div>
  Hobby <br>
  <%= text_field_tag :hobby %>
</div>
<div>
  Years Experience <br>
  <%= number_field_tag :years_experience %>
</div>
<div>
  Available date <br>
  <%= date_field_tag :available_date %>
</div>
<div>
  <%= submit_tag %>
</div>
</form>
<% end %>

app/views/home/index.html.erb
<p>
  <%= link_to 'View Locations', locations_path %>
  <% @locations.each do |current_location| %>
  <%= render 'locations/single_location', location: current_location %>
  <% end %>
</p>
<p>
  <%= link_to 'Events', events_path %>
  <% @events.each do |current_event| %>
  <%= render 'events/single_event', event: current_event %>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <h3>
        <a href="<%= root_path %>">
          <span class="title event">Event</span><span class="title only">Only</span>
        </a>
      </h3>
    </header>
    <%= yield %>
  </body>
</html>

app/views/locations/_location_form.html.erb
<h1>New Location</h1>

<%= link_to 'Show all locations', locations_path %>

<%= form_for location do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :image %>
    <%= f.text_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/locations/_single_location.html.erb
<div class="location">
  <% if show_name%>
  <h3><%= location.name %></h3>
  <% end %>
  <h4>City: <%= location.city %></h4>
  <%= location.description %><br />
  <%= link_to image_tag(location.image, class: "location"), location_path(location) %>

</div>

app/views/locations/edit.html.erb
locations#edit page

<h1>Editing <%= link_to @location.name, location_path(@location) %></h1>

<%= render 'location_form', location: @location %>

<!-- <%= link_to'Edit', edit_location_path(@location) %> | <%= link_to 'Delete', location_path(@location), method: :delete, data: {confirm: "Are you sure you want to delete the location '#{@location.name}'? This cannot be undone!"} %> -->

app/views/locations/index.html.erb
locations#index page

<!-- <h1>Locations</h1> -->

<!-- <% @locations.each do |current_location| %>
  <div class="location">
    <h3><%= current_location.name %></h3>
    <h4>City: <%= current_location.city %></h4>
    <%= current_location.description %><br />
    <%= link_to image_tag(current_location.image, class: "location"), location_path(current_location) %>
  </div>
<% end %> -->
<h1>Location Only</h1>
<p>
  <%= link_to 'New Location', new_location_path %>
</p>
<% @locations.each do |current_location| %>
<%= render 'single_location', location: current_location, show_name: true %>
<%= render 'location_form', location: current_location %>
<% end %>

app/views/locations/new.html.erb
locations#new page

<h1>New Location</h1>
<%= link_to 'Show all locations', locations_path %>
<%= render 'location_form', location: @location %>
<!-- <%= link_to 'Show all locations', locations_path %>

<%= form_for @location do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :image %>
    <%= f.text_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %> -->

app/views/locations/show.html.erb
locations#show page
<h1><%= @location.name %></h1>

<!-- <div class="location">
  <h3><%= @location.name %></h3>
  <h4>City: <%= @location.city %></h4>
  <%= @location.description %><br />
  <%= link_to image_tag(@location.image, class: "location"), location_path(@location) %>
</div> -->

<%= render 'single_location', location: @location, show_name: false %>

<%= link_to 'Edit', edit_location_path(@location) %>
| <%= link_to 'Delete', location_path(@location), method: :delete, data: {confirm: "Are you sure you want to delete the location '#{@location.name}'? This cannot be undone!"} %>